version: '3.8'

services:
  app:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && sh build-production.sh && npm start"
    ports:
      - "3000:3000"
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=https://db.gestionrpjccm.com
      - BACKEND_URL=https://api.gestionrpjccm.com
    restart: unless-stopped
